// @golddevelopment/virtuagym-node/client
export { VirtuaGymClientV1, VirtuaGymApiError } from './virtuagym-client-v1';
export type {
  ActivateUserData,
  ActivateUserResult,
  ClubEventOptions,
  ClubEventsOptions,
  CreateEmployeeData,
  CreateEventParticipantData,
  CreateInvoiceData,
  AddMemberCreditsData,
  AssignWorkoutData,
  BodymetricsOptions,
  UpdateBodymetricData,
  Weekday,
  CreateMemberNoteData,
  MemberCreditsOptions,
  MemberNotesOptions,
  UpdateMemberNoteData,
  CreateInvoiceRowData,
  InvoicePaymentMethod,
  CreateMemberData,
  CreateMembershipInstanceData,
  CreateOrUpdateEmployeeData,
  CreateOrUpdateMemberData,
  CustomDiscount,
  EmployeeMutationData,
  EmployeeOptions,
  EmployeesOptions,
  EventParticipantOptions,
  EventParticipantsOptions,
  MemberIdentifier,
  MemberMutationData,
  MemberOptions,
  MembersOptions,
  MembershipDefinitionsOptions,
  MembershipInstancesOptions,
  CreateVisitData,
  UpdateEmployeeData,
  UpdateEventParticipantData,
  UpdateMemberData,
  VisitsOptions,
  VisitStatus,
} from './virtuagym-client-v1';
export type { VirtuaGymClientV1Options } from './virtuagym-client-v1-options';
export { VirtuaGymClientV3, VirtuaGymV3ApiError } from './virtuagym-client-v3';
export type {
  BookingGuestData,
  BookingRuleOverrides,
  CancelBookingOptions,
  CreateBookingData,
  CreateLeadData,
  EventBookingsOptions,
  LeadMutationData,
  LeadsOptions,
  ScheduleEventsOptions,
  ScheduleEventType,
  UpdateBookingData,
  UpdateLeadData,
} from './virtuagym-client-v3';
export type { VirtuaGymClientV3Options } from './virtuagym-client-v3-options';
